export const skills = [
  "Python",
  "JavaScript",
  "TypeScript",
  "HTML",
  "CSS",
  "C++",
  "React",
  "Next.js",
  "Tailwind",
  "SVG",
  "Cursor",
  "Claude Code",
  "n8n",
  "ComfyUI",
  "Weave",
  "Figma plugins",
  "Figma",
  "Framer",
  "UX",
  "UI",
  "Material Design",
  "Magento",
  "Shopify",
  "Brand identity",
  "Pitch decks",
  "After Effects",
  "Premiere",
  "DaVinci Resolve",
  "GSAP",
  "Rive",
  "Lottie",
  "SMIL",
  "Explainer video",
  "Photoshop",
  "Illustrator",
  "Procreate",
  "Affinity",
  "Blender",
  "Spline",
  "Fusion 360",
  "Ableton",
  "Audition",
  "Suno",
  "ElevenLabs",
  "Sound design",
  "Midjourney",
  "FLUX",
  "ChatGPT Images",
  "QWEN",
  "Nano Banana",
  "Sora",
  "Veo",
  "Kling",
  "Wan",
  "Unreal",
  "Unity",
  "Game design",
  "Art direction",
  "Notion",
  "Obsidian",
  "Jira",
  "QA",
  "iOS",
  "Telegram bots",
  "Interactive maps",
  "Motion design",
  "Illustration",
  "Prototyping",
  "Design systems",
  "Video editing",
  "Print design",
  "3D",
  "Animation",
  "Product design",
  "Branding",
  "Playdate",
  "Raycast",
  "Storytelling",
  "E-commerce",
  "Photo retouch",
] as const;

export type Skill = (typeof skills)[number];
